services:
  - type: web
    name: procedures-lab
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
