name: Deploy - Render

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -q

  deploy:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      RENDER_SERVICE_URL: ${{ secrets.RENDER_SERVICE_URL }}
    environment:
      name: render
      url: ${{ env.RENDER_SERVICE_URL }}
    steps:
      - name: Trigger Render deploy (Deploy Hook)
        if: ${{ env.RENDER_DEPLOY_HOOK_URL != '' }}
        run: |
          echo "Calling Render Deploy Hook..."
          curl -fsSL -X POST "${RENDER_DEPLOY_HOOK_URL}"
          echo "Deploy triggered. Check Render dashboard for progress."
      - name: Publish live URL (if provided)
        if: ${{ env.RENDER_SERVICE_URL != '' }}
        run: |
          echo "Live deployment: ${RENDER_SERVICE_URL}" >> "$GITHUB_STEP_SUMMARY"
      - name: Skip (no Deploy Hook secret set)
        if: ${{ env.RENDER_DEPLOY_HOOK_URL == '' }}
        run: |
          echo "RENDER_DEPLOY_HOOK_URL GitHub Secret is not set. Skipping deploy." \
               "Add this secret with the Deploy Hook URL from your Render service to enable deployments."
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Deploy skipped (no Deploy Hook)." >> "$GITHUB_STEP_SUMMARY"
          echo "Set repository secrets to enable link output:" >> "$GITHUB_STEP_SUMMARY"
          echo "- RENDER_DEPLOY_HOOK_URL: your Render Deploy Hook URL" >> "$GITHUB_STEP_SUMMARY"
          echo "- RENDER_SERVICE_URL: your live service URL (e.g., https://<service>.onrender.com)" >> "$GITHUB_STEP_SUMMARY"
