name: Deploy - Render

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -q

  deploy:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Guard (skip if no secret)
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "No RENDER_DEPLOY_HOOK_URL secret set; skipping deploy.";
            exit 0;
          fi
        shell: bash
      - name: Trigger Render deploy (Deploy Hook)
        if: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Calling Render Deploy Hook..."
          curl -fsSL -X POST "${RENDER_DEPLOY_HOOK_URL}"
          echo "Deploy triggered. Check Render dashboard for progress."
      - name: Skip (no Deploy Hook secret set)
        if: ${{ !secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "RENDER_DEPLOY_HOOK_URL GitHub Secret is not set. Skipping deploy." \
               "Add this secret with the Deploy Hook URL from your Render service to enable deployments."
