name: Deploy - Render

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -q

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy (Deploy Hook)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "${RENDER_DEPLOY_HOOK_URL}" ]; then
            echo "RENDER_DEPLOY_HOOK_URL GitHub Secret is not set."
            echo "Set it to the Deploy Hook URL from your Render service settings."
            exit 1
          fi
          echo "Calling Render Deploy Hook..."
          curl -fsSL -X POST "${RENDER_DEPLOY_HOOK_URL}"
          echo "Deploy triggered. Check Render dashboard for progress."
